### ISSUE TITLE
추가요망기능: 각 채널의 통계

### ISSUE THREAD

**Issue by amkorousagi** [amkorousagi/Trendup#14]
content  owner에 대한 용어조사 필요
각 채널에 인기 10 위 동영상 얻을수있음
content  owner은 youtube partnership과 관련있는듯

![Screenshot_20200706-091403_Chrome](https://user-images.githubusercontent.com/39821875/86545646-1dc3d280-bf6b-11ea-8904-6b2dd1de6324.jpg)
![Screenshot_20200706-092742_Chrome](https://user-images.githubusercontent.com/39821875/86545649-25837700-bf6b-11ea-8719-9a9bc4c1d85f.jpg)

https://developers.google.com/youtube/analytics/channel_reports?hl=ko

**Comment by yuntaeJ** [comment]
"인기 10 위 동영상 얻을수있음"
유튜브 채널중에 다양한 주제로 여러 영상을 찍는 채널보다는 
한가지 주제로 예를 들면 먹방만 찍어서 인기 top10영상이 모두 먹방이라든지
하는 채널을  몇개 선정해서 데이터를 뽑으면 의미 있는 데이터가 될듯
