### ISSUE TITLE
쇼핑몰 인기 키워드 crawling 및 이미지 crawling (0706)

### ISSUE THREAD

**Issue by yuntaeJ** [amkorousagi/Trendup#20]

**Comment by yuntaeJ** [comment]
인기키워드 crawling:
쇼핑몰에서 계절 추천 아이템 검색 (ex) 여름 옷 추천) 을 통해 키워드 추출
몇가지 주요 keyword들을 미리 뽑아놓고 노출 빈도수를 계산하기

이미지 crawling:
네이버 클라드우드의 OCR 기능 이용 생각 중

**Comment by amkorousagi** [comment]
끝났으니 닫겠음
