### ISSUE TITLE
DB 활용 계획 및 설계 (0706)

### ISSUE THREAD

**Issue by amkorousagi** [amkorousagi/Trendup#22]

**Comment by amkorousagi** [comment]
Db에서 keyword를 넣는데
크게 두 개의 테이블로 하자
하나는 관측 결과를 기록하는 real_keyword 테이블
다른 하나는 예측 결과를 기록하는 predict_keyword 테이블

그리고 그 테이블의 한 row는
업로드 날ㅉㅏ(또는 예측 날짜), 카테고리, 키워드 리스트
이렇케 3가지로 하자

추가할만한 사항은 thumnale에서 나온 키워드랑 title에서 나온 키워드를 분린사여 테이블을 더 만들 건가?
정도. 나중에 더 고민해보자

**Comment by yuntaeJ** [comment]
저번에 말한 구글에서 제공하는 기능중에 키워드 추천 기능 써서 title이랑 thumnale 중에 키워드를 뽑는 식으로 하면 안될까?
그리고 row에 그 키워드의 빈도수나 중요도 같은 정보도 추가해야되지 않나.
네이버나 타 쇼핑 사이트에서 얻은 키워드도 같은 방식으로 하면 될꺼같고
