### ISSUE TITLE
도커 컨테이너 만들기(0714)

### ISSUE THREAD

**Issue by yuntaeJ** [amkorousagi/Trendup#26]
DATA 컨테이너 들
-네이버 쇼핑 크롤링
-쿠팡, 11번가 웹 쇼핑몰 크롤링
-유튜브 API

**Comment by yuntaeJ** [comment]
참고 : https://www.44bits.io/ko/post/easy-deploy-with-docker

**Comment by yuntaeJ** [comment]
도커파일 작성 문법 : http://longbe00.blogspot.com/2015/03/dockerfile.html

**Comment by yuntaeJ** [comment]
도커파일 구조 통일(0719)

FROM    우분투 18.04

WORKDIR    /trendup/(각 컨테이너 name)

RUN     python3 깔고
            pip install ~ (<-python3이미지)
            ehco
            curl
            apt-get
            git clone

EXPOSE  (컨테이너 간 통신에서 포트?)

ENV (환경변수) (<-저장 같은거 할때?, 추출주기?)

CMD ["<실행 파일>", "<매개 변수1>", "<매개 변수2>"]

**Comment by yuntaeJ** [comment]
1. n_shopping
/trendup/n_shopping/dockerfile/Dockerfile

**Comment by yuntaeJ** [comment]
https://youtu.be/JNc11rxLtmE

**Comment by amkorousagi** [comment]
docker file 작성법 : https://docs.docker.com/develop/develop-images/dockerfile_best-practices/
docker build --tag (image name) -f (docker file's path) .
docker run --rm -it --name (container name) (image name or ID) (command)

docker 컨테이너 만들고 test해보았으므로 닫겠음
