### ISSUE TITLE
Apahce, 서버 방화벽 및 포트 설정

### ISSUE THREAD

**Issue by yuntaeJ** [amkorousagi/Trendup#27]
방화벽 설정 및 포트 열기
https://www.lesstif.com/system-admin/rhel-centos-7-firewalld-22053128.html

**Comment by yuntaeJ** [comment]
아파치 서버 https://galid1.tistory.com/264

**Comment by yuntaeJ** [comment]
![image](https://user-images.githubusercontent.com/67727745/87852263-6dc37180-c93b-11ea-8deb-4a34060a3de5.png)

**Comment by amkorousagi** [comment]
ncp ACG, 서버 내부 방화벽(ufw), conatiner port forwarding 모두 check하고 test함.
정상적으로 web를 서비스할 수 있음을 확임함
