### ISSUE TITLE
데이터 수집 컨테이너

### ISSUE THREAD

**Issue by yuntaeJ** [amkorousagi/Trendup#29]
네이버 쇼핑 키워드 수집 컨테이너

**Comment by yuntaeJ** [comment]
![image](https://user-images.githubusercontent.com/67727745/89170113-28997380-d5ba-11ea-898b-5453e9b77295.png)

이미지가 오류없이 빌드되긴 했는데 git으로 가져온 파이썬 코드가 실행이 안됨 -> db서버에 데이터 업데이트가 안됨

**Comment by amkorousagi** [comment]
CMD 로 해봐
빌드된  이미지가 컨테이너로서 작동되는 순간 처음으로 실행시킬 명령어로 flask를 써서 파이썬코드 실행해봐

**Comment by amkorousagi** [comment]
docker container에서도 python 코드가 문제없이 작동하고 db서버에 업데이트 됨을 확인함
문제없이 해결됨
