### ISSUE TITLE
구글 차트 api && php mysql

### ISSUE THREAD

**Issue by yuntaeJ** [amkorousagi/Trendup#30]
https://www.webslesson.info/2016/10/make-simple-pie-chart-by-google-chart-api-with-php-mysql.html

**Comment by yuntaeJ** [comment]
![image](https://user-images.githubusercontent.com/67727745/89297009-2e688500-d69e-11ea-9d92-3bbd63d4e718.png)
![image](https://user-images.githubusercontent.com/67727745/89297077-46400900-d69e-11ea-8954-6034b7e53777.png)
접속은 성공했는데 뒤에 쿼리 문이 실행되지 않음

**Comment by amkorousagi** [comment]
https://github.com/amkorousagi/Trendup/issues/45#issue-676389228
에서 완료함
