### ISSUE TITLE
kubernetes 설치

### ISSUE THREAD

**Issue by yuntaeJ** [amkorousagi/Trendup#34]
쿠버네티스설치

**Comment by JEONYUNTAE** [comment]
https://github.com/mojokb/kubeflow-book/tree/master/kubernetes_install
참고하여 설치

도중 nvidia-xxx 패키지 설치에서 에러 
존재하지 않는 패키지 -> 대체 필요
https://docs.nvidia.com/deeplearning/cudnn/install-guide/index.html 참고

**Comment by amkorousagi** [comment]
1432

**Comment by yuntaeJ** [comment]
쿠브플로우 
https://www.kubeflow.org/docs/started/k8s/

쿠브네티스
https://kubernetes.io/docs/tasks/tools/

**Comment by yuntaeJ** [comment]
https://medium.com/finda-tech/overview-8d169b2a54ff

**Comment by yuntaeJ** [comment]
쿠버네티스 마스터 노드 생성
![image](https://user-images.githubusercontent.com/67727745/89868069-299b5800-dbed-11ea-91c4-dc78f23ce8c7.png)

**Comment by amkorousagi** [comment]
ncp에서는 vmx 와 같은 가상화 기술을 지원하지 않아서
서버에 설치하는 것은 포기하고
로컬에 설치해보겠다
