### ISSUE TITLE
container 제어 코드(모듈) test

### ISSUE THREAD

**Issue by amkorousagi** [amkorousagi/Trendup#38]

**Comment by amkorousagi** [comment]
![스크린샷, 2020-08-09 19-09-20](https://user-images.githubusercontent.com/39821875/89729808-1a44cf00-da74-11ea-8e33-3c2479a54413.png)
서버에서 tcp 모듈을 사용해서 서로 통신을 주고 받고 제어할 수 있음을 test해서 확인했다

**Comment by yuntaeJ** [comment]
![image](https://user-images.githubusercontent.com/67727745/89729906-02ba1600-da75-11ea-96e0-20c03df82775.png)
tcp 모듈을 활용해 컨테이너 간 실행흐름을 제어하고, 기능이 실행되어 mysql에 적절한 data가 update
