### ISSUE TITLE
DB - 웹 연동(html<-->php<-->mysql, google chart api by javascript in html)

### ISSUE THREAD

**Issue by yuntaeJ** [amkorousagi/Trendup#45]
http://27.96.131.68/demo1.html

html문서에서 php로 mysql과 통신하고 javascript로 google chart api이용

![image](https://user-images.githubusercontent.com/67727745/89826532-54f05980-db91-11ea-9ba7-896892ecec99.png)

**Comment by amkorousagi** [comment]
javascript로 google chart api를 사용할수 있음을 확있했으므로 닫겠다
