### ISSUE TITLE
네이버 쇼핑 web crawling(0703)

### ISSUE THREAD

**Issue by amkorousagi** [amkorousagi/Trendup#8]
python으로 web crawling 예제 만들어
data를 출력해보기

**Comment by yuntaeJ** [comment]
네이버 DataLab API를 이용하는 경우 우리가 원하고자 하는 데이터를 불러 올 수 없어 직접 크롤링 하였음.
우선 네이버에서 크롤링을 막아 css가 빠진 쇼핑 인기 키워드 사이트에 접속하여 우회하는 방식으로 크롤링을 하였음.

**Comment by amkorousagi** [comment]
지고트원피스



                                                        케네스레이디원피스



                                                        샤틴원피스



                                                        쥬시쥬디
